### ISSUE TITLE
migrating the frontend from create react app to vite or nextjs

### ISSUE THREAD

**Issue by Gourav-21** [TeekshaHarish/DocAppointment#2]
### Problem
The frontend has been created with create react app which is not maintained anymore by the react team and 
babel-preset-react-app is part of the create-react-app 

so, It is thus unlikely that this bug will ever be fixed.

![image](https://github.com/TeekshaHarish/DocAppointment/assets/107918791/a1a46d7c-925b-41f7-91b4-916d53f454de)

### Solution

1. I suggest we should migrate/switch the frontend code from create react app to something like vite or change the framework to nextjs. migrating would not only make the code futureproof but will also help speed up the development process

#### or

2. this error can be worked around by adding the @babel/plugin-proposal-private-property-in-object package in the devDependencies
```
npm install --save-dev @babel/plugin-proposal-private-property-in-object
```

**Comment by TeekshaHarish** [comment]
ok you can migrate the frontend to vite. Assigning this issue to you

**Comment by Gourav-21** [comment]
@TeekshaHarish hey i need your help, i have texted u on discord
